collision_spheres:
  rh_palm:
    - "center": [0.020, -0.006, 0.016]
      "radius": 0.020
    - "center": [0.024, 0.000, 0.050]
      "radius": 0.014
    - "center": [-0.018, -0.004, 0.015]
      "radius": 0.020
    - "center": [0.024, 0.000, 0.072]
      "radius": 0.013
    - "center": [-0.012, 0.000, 0.072]
      "radius": 0.013
    - "center": [-0.012, 0.000, 0.050]
      "radius": 0.013
    - "center": [0.008, 0.000, 0.050]
      "radius": 0.013
    - "center": [0.008, 0.000, 0.076]
      "radius": 0.012
    - "center": [0.000, 0.000, 0.028]
      "radius": 0.020

  rh_ffproximal:
    - "center": [-0.004, 0.000, 0.000]
      "radius": 0.010
    - "center": [-0.019, 0.000, 0.000]
      "radius": 0.0095
    - "center": [-0.033, 0.000, 0.000]
      "radius": 0.0090
  rh_ffmiddle:
    - "center": [-0.004, 0.000, 0.000]
      "radius": 0.0090
    - "center": [-0.016, 0.000, 0.000]
      "radius": 0.0090
  rh_ffdistal:
    - "center": [-0.003, 0.000, 0.000]
      "radius": 0.0080
    - "center": [-0.013, 0.001, 0.000]
      "radius": 0.0080
    - "center": [-0.023, 0.001, 0.000]
      "radius": 0.0075

  rh_mfproximal:
    - "center": [-0.004, 0.000, 0.000]
      "radius": 0.010
    - "center": [-0.019, 0.000, 0.000]
      "radius": 0.0095
    - "center": [-0.033, 0.000, 0.000]
      "radius": 0.0090
  rh_mfmiddle:
    - "center": [-0.004, 0.000, 0.000]
      "radius": 0.0090
    - "center": [-0.016, 0.000, 0.000]
      "radius": 0.0090
  rh_mfdistal:
    - "center": [-0.003, 0.000, 0.000]
      "radius": 0.0080
    - "center": [-0.013, 0.001, 0.000]
      "radius": 0.0080
    - "center": [-0.023, 0.001, 0.000]
      "radius": 0.0075

  rh_rfproximal:
    - "center": [-0.004, 0.000, 0.000]
      "radius": 0.010
    - "center": [-0.019, 0.000, 0.000]
      "radius": 0.0095
    - "center": [-0.033, 0.000, 0.000]
      "radius": 0.0090
  rh_rfmiddle:
    - "center": [-0.004, 0.000, 0.000]
      "radius": 0.0090
    - "center": [-0.016, 0.000, 0.000]
      "radius": 0.0090
  rh_rfdistal:
    - "center": [-0.003, 0.000, 0.000]
      "radius": 0.0080
    - "center": [-0.013, 0.001, 0.000]
      "radius": 0.0080
    - "center": [-0.023, 0.001, 0.000]
      "radius": 0.0075

  rh_lfproximal:
    - "center": [-0.004, 0.000, 0.000]
      "radius": 0.010
    - "center": [-0.019, 0.000, 0.000]
      "radius": 0.0095
    - "center": [-0.033, 0.000, 0.000]
      "radius": 0.0090
  rh_lfmiddle:
    - "center": [-0.004, 0.000, 0.000]
      "radius": 0.0090
    - "center": [-0.016, 0.000, 0.000]
      "radius": 0.0090
  rh_lfdistal:
    - "center": [-0.003, 0.000, 0.000]
      "radius": 0.0080
    - "center": [-0.013, 0.001, 0.000]
      "radius": 0.0080
    - "center": [-0.023, 0.001, 0.000]
      "radius": 0.0075

  rh_thbase:
    - "center": [-0.004, 0.010, 0.000]
      "radius": 0.011
    - "center": [-0.012, 0.020, 0.000]
      "radius": 0.011
  rh_thproximal:
    - "center": [-0.005, -0.002, 0.000]
      "radius": 0.012
    - "center": [-0.021, 0.000, 0.000]
      "radius": 0.012
    - "center": [-0.034, -0.001, 0.000]
      "radius": 0.011
  rh_thmiddle:
    - "center": [-0.004, 0.000, 0.000]
      "radius": 0.010
    - "center": [-0.017, 0.000, 0.000]
      "radius": 0.010
  rh_thdistal:
    - "center": [-0.005, 0.001, 0.000]
      "radius": 0.010
    - "center": [-0.017, 0.002, 0.000]
      "radius": 0.008
